title: Gearmamn06
description: Gearmamn06 personal blog
show_downloads: true

baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://gearmamn06.github.io" # change this to the base hostname & protocol for your site

google_analytics: UA-64521529-2
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Lore Pirri"
image: /thumbnail-jumbo.png
twitter:
  username: 
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 
  # 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
